DROP TABLE IF EXISTS items;
DROP TABLE IF EXISTS users;

CREATE TABLE IF NOT EXISTS users (
    user_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(50)   NOT NULL,
    email varchar(50)  NOT NULL,
    CONSTRAINT uc_user_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS items (
    item_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(50) NOT NULL,
    description varchar(200) NOT NULL,
    available boolean NOT NULL,
    user_id bigint   NOT NULL,
    request_id bigint,
    CONSTRAINT fk_items_user_id FOREIGN KEY(user_id) REFERENCES users (user_id) ON DELETE CASCADE
);
